PwcSF/backup/force-app/main/default/objects/OrderDetail__c/OrderDetail__c.object-meta.xml
<CustomObject>
    <label>OrderDetail</label>
    <nameField>
        <label>OrderDetail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PwcSF/backup/force-app/main/default/objects/OrderDetail__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

PwcSF/backup/force-app/main/default/objects/OrderDetail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PwcSF/backup/force-app/main/default/objects/OrderDetail__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>OrderDetails</relationshipLabel>
    <relationshipName>OrderDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

PwcSF/backup/force-app/main/default/classes/OrderClass.cls
public with sharing class OrderClass {
    @AuraEnabled
    public static Contact createContact(contact con) {
        insert con;
        return con;
    }

    @AuraEnabled
    public static void updateOrder(String orderId,String contactId,String address,Decimal amount) {
        OrderDetail__c od=new OrderDetail__c();
        od=[Select Address__c,
        Status__c,
        Contact_Id__c 
        From OrderDetail__c
        Where Id=:orderId];
        od.Contact_Id__c=contactId;
        od.Status__c='Order Placed';
        od.Address__c=address;
        od.Amount__c=amount;
        update od;
    }

    @AuraEnabled(cacheable=true)
    public static List<Contact> getContact() {
        return[Select Id,Email From Contact];
    }
}